org.gradle.jvmargs=-Xmx400m -XX:MaxMetaspaceSize=192m -XX:TieredStopAtLevel=1 -XX:CICompilerCount=1 -XX:+UseSerialGC -Dfile.encoding=UTF-8 -Dcom.android.tools.r8.threads=1
org.gradle.parallel=false
org.gradle.workers.max=1
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false

